### ISSUE TITLE
High precision dates throw UnboundLocalError

### ISSUE THREAD

**Issue by talister** [IAU-ADES/ADES-Master#3]
As part of writing some code to convert Astrometrica output 80 column files & associated logs into ADES format with uncertainties, I have run into a problem using `sexVals.checkDate()`. I have been converting the commented out "tests" in lines 154--169 and 175--207 into actual `pytest` unit tests and have run into a problem with some of them.  The following:
```python
#testdate("1800 01 01.3333333 ")
#testdate("1800 01 01.3333333")
#testdate("1920 01 01.3333333")
#testdate("1920 09 01.3333333")
#testdate("1920 10 01.3333333")
```
all throw a `UnboundLocalError` error when passed to `checkDate`:
```python
rdict = { 'date' : "1920 10 01.3333333" }
In [63]: sexVals.checkDate(rdict)
Bad Date: 60.0 for ss in date: 1920 10 01.3333333
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-63-979967bf5e35> in <module>()
----> 1 sexVals.checkDate(rdict)

/home/tlister/git/ADES-Master/Python/bin/sexVals.py in checkDate(rdict)
    330    # test by turning it back -- valid prec is 1 through 100000
    331    #
--> 332    sexdate = isoToSexDate(dateiso, prec)
    333    if sexdate != date:  # no round-trip
    334        errorSexVal( " Date invalid reverse: " + date, sexdate)

/home/tlister/git/ADES-Master/Python/bin/sexVals.py in isoToSexDate(isodate, prec)
    314       yy = "{0:.1f}".format(xx/86400.0)[1:]
    315    #print (yy)
--> 316    sexdate = yyyy + ' ' + month + ' ' + day + yy
    317    #print (sexdate)
    318    return "{0:17s}".format(sexdate)  # get length right

UnboundLocalError: local variable 'yy' referenced before assignment
```

This seems like a problem that should be caught in a different (if those date strings are invalid) or shouldn't trigger the exception (if valid)

**Comment by ghockney** [comment]
These are invalid input strings because they have time to better than millionths of a day.   The mpc format is columns 16-32 and therefore only allows 01.333333.   Any mpc-format string will therefore convert correctly. As the comment on line 330 says, "valid prec is 1 thorugh 100000" and those strings are prec=0.  



I've pushed a fix to give the more appropriate error report of the time string not inverting correctly (it comes back to 01.333333 now).    Notice this was also setting ss to 60.0 because of the extra digits, which was also not legal (the old format has no leap seconds), but that error got buried by the other.   I don't think a more specific error is appropriate because there are lots of other possible non-inverting inputs.

**Comment by ghockney** [comment]
The mpc80coltoxml script has been tested on a fairly complete dump of actual mpc data to make sure it inverts with xmltompc80col.  Notice how the 80-col format sometimes has things like embedded lower-case letters between the yyyy and mm in the date field where a ' ' is supposed to be; the mpc80coltoxml script does find those and replace them with ' ' for the date conversion (and handle them correctly otherwise too).

Unfortunately most of the testing is end-to-end because the xml format wasn't final when the code was originally written.

**Comment by talister** [comment]
Thanks that has fixed the issue for me. I am in the process of writing a converter for Astrometrica's output to ADES PSV format (which will be available to the community) so I am testing things that have been produced by software whose output hasn't been through the MPC ingest validation.

If you are interested and they are helpful, I am happy to contribute the `pytest`-based unit tests for `sexVals` back; I can setup up a fork and send a Pull Request
