### ISSUE TITLE
<artSat> designations

### ISSUE THREAD

**Issue by Bill-Gray** [IAU-ADES/ADES-Master#41]
Peter Vereš and I have been discussing various artsat-related issues,  and it made me think about the above subject.

"Officially recognized" (*) artsats have two designations.  They have a NORAD number,  currently limited to five digits,  but plans are afoot to allow that to go up to nine digits.  They also have an international designation,  which is a launch year with a dash,  a three-digit launch number,  and one,  two,  or three uppercase letters.  For example,  the ISS is NORAD 25544 and has the international designation 1998-067A (meaning it was the main component of the 67th launch of 1998).  So an international designation can be nine,  ten,  or eleven bytes long.

I don't think anyone is using this part of ADES yet.  It seems to me we might want to specify exactly which scheme gets used.  Or we might want to have `<artSat>` and `<artSatIntl>`.  Or,  since the existing scheme allows 25 bytes,  one might have (for the ISS) `<artSat>25544/1998-067A</artSat>`.

I don't take a strong opinion on this,  except that agreement on what should go between `<artSat>` and `</artSat>` seems desirable.

(*) Empty trash-bag objects and some other undesignated objects tracked by the planetary defense community have been getting designations assigned by me that follow the above schemes,  but which should not conflict with official designations.

**Comment by federicaspoto** [comment]
Hi @Bill-Gray, Peter contacted you because we are working on this Jira ticket: https://mpc-service.atlassian.net/browse/MPCHLP-2262. I'll give more information about those specific problems on the Jira tickets.

Following your exchange with Peter we decided to use the internal designation for the artsat, which is supposed to be unique. Even though the existing scheme allows string of 25 characters long, the MPC still need to produce an obs80 format and while we can fit one of the two designations, we cannot fit both in there (the maximum allow length is 12). We are already taken actions to clean and fix our current database.

If you agree, we would like to do the following:

- Use the international designation for the artsat field, e.g. `<artsat>1998-067A</artsat>`
- Keep only the artsat field 

If that sounds good, I believe we can close this issue and I can update you on the corresponding Jira ticket. 

Thank you,
Federica

**Comment by Bill-Gray** [comment]
Hi Federica,

    Thank you.  I'm quite happy with the idea that we'll use only the 
international (YYYY-NNNAAA) designation in both the punch-card format 
and for the ADES <artSat></artSat> field.  I commented on it here 
because it's both an MPC issue and a broader ADES issue;  non-MPC people 
(including me) setting that field should know what to put into it.  So 
I'm thinking that the ADES documentation ought to give some suitable 
advice on its use.  For example :

- Can <artSat> be used on submissions,  or should it only be set by MPC?

- Can it have a value such as 0000-000ZZZ for unidentified artsats?  If 
not,  what should submitters put in <artSat></artSat> to say "it's an 
artsat,  but I don't know which one"?  What should MPC put there?  (I 
could imagine it being left blank,  to say : yes,  it's an artsat,  but 
that's all we know.  And there may,  or may not,  be a distinction to be 
made between "it couldn't be identified" and "it hasn't been checked yet 
to see if it's a known object".)

    Glad to see progress happening on this!

-- Bill

**Comment by federicaspoto** [comment]
Hi Bill,

thank you for your reply. 

- <artsat></artsat> can be used by submitters and some of them are already doing it. As you have correctly mentioned in the Jira tickets, we are not handling it in the best way at the moment when we convert it to obs80, but we are working on it. If they know what it is, please write it. 
- If the artsat desingation is not known, usually people use the trksub field and leave the artsat field empty, but they let us know when they submit the observations (e.g. using the artsat flag on the webpage) or similar thing. Same if we identify it as an artsat but we don't know what it is. Does this make sense to see? 

Please let me know if you have other questions.

**Comment by stevechesley** [comment]
Resolved with PR #47
